#!/bin/bash
# GetMe configuration file
# this file configures your site.
#
# 1. copy this file to /path/to/your/websites/images/dir/.getme
# 2. make sure the configuration is ok
# 3. run get_images pointing to where your website directories are
#    ej. get_images /path/to/your/websites/

# get_images vars
#

# main url
url="http://someone.somesite.com/"

# possible image servers (csv urls)
# strip http:// and everything after / of the url
tmp=${url#http://}
tmp=${tmp%%/*}

# assign alternative image server urls
urls="${tmp},someone.somewhereelse.com,vault.blogs.com"

# add possible file servers (mainly used in blogs)
for n in `seq 0 100`; do
    urls="$urls,blog-imgs-$n.blogs.com"
done

# user agent to use
userAgent="Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.70 Safari/533.4"

# file types (csv)
types="bmp,gif,jpeg,jpg,png,svg,tiff,swf"
